# Generated by Django 4.2.8 on 2024-03-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtransaksi',
            options={'verbose_name': 'Item Transaksi', 'verbose_name_plural': 'Item Transaksi'},
        ),
        migrations.AlterModelOptions(
            name='sumberdana',
            options={'verbose_name': 'Sumber Dana', 'verbose_name_plural': 'Sumber Dana'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile'},
        ),
        migrations.AlterModelOptions(
            name='varianproduk',
            options={'verbose_name': 'Varian Produk', 'verbose_name_plural': 'Varian Produk'},
        ),
    ]
