# Generated by Django 4.2.8 on 2024-04-20 17:33

from django.db import migrations


def create_initial_data(apps, schema_editor):
    SumberDana = apps.get_model("home", "SumberDana")
    for i, n in enumerate(["Cash on Hand", "Rekening A"]):
        SumberDana.objects.create(id=i + 1, nama=n)

    Lokasi = apps.get_model("home", "Lokasi")
    Lokasi.objects.create(id=1, nama_toko="Mitra Berkah Sukabumi")

    MetodePembayaran = apps.get_model("home", "MetodePembayaran")
    for i, n in enumerate(["Tunai", "Bank Transfer"]):
        MetodePembayaran.objects.create(id=i + 1, nama=n)

    Unit = apps.get_model("home", "Unit")
    for i, n in enumerate(["Box", "Strip", "Botol"]):
        Unit.objects.create(id=i + 1, nama=n)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
