# Generated by Django 4.2.8 on 2024-04-21 13:00

from django.db import migrations


def create_initial_data(apps, schema_editor):
    SumberDana = apps.get_model("home", "SumberDana")
    for i, n in enumerate(["Cash on Hand", "Rekening A", "Hutang"]):
        SumberDana.objects.create(nama=n)

    Lokasi = apps.get_model("home", "Lokasi")
    Lokasi.objects.create(id=1, nama_toko="Mitra Berkah Sukabumi")

    MetodePembayaran = apps.get_model("home", "MetodePembayaran")
    for i, n in enumerate(["Tunai", "Bank Transfer"]):
        MetodePembayaran.objects.create(nama=n)

    Unit = apps.get_model("home", "Unit")
    for i, n in enumerate(["Box", "Strip (Blister)", "Botol", "Pcs"]):
        Unit.objects.create(nama=n)

    Storage = apps.get_model("home", "Storage")
    for i, n in enumerate(["Rak Atas", "Rak Bawah", "Kulkas"]):
        Storage.objects.create(nama=n)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_initial_data)]
