# Generated by Django 4.2.8 on 2024-03-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_itemtransaksi_options_alter_sumberdana_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransaksi',
            name='tipe_transaksi',
            field=models.CharField(choices=[('resep', 'Resep'), ('non-resep', 'Tanpa Resep')], default='non-resep', max_length=15),
        ),
    ]
