# Generated by Django 4.2.8 on 2024-04-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_auto_20240421_1300"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pembayaran",
            options={
                "verbose_name": "Operasional",
                "verbose_name_plural": "Operasional",
            },
        ),
        migrations.AlterModelOptions(
            name="pembelian",
            options={"verbose_name": "Order", "verbose_name_plural": "Order"},
        ),
    ]
