# Generated by Django 4.2.8 on 2024-04-19 14:17

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_itemtransaksi_tipe_transaksi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pembelian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=home.models.create_object_id,
                        max_length=32,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("nomor_pre_order", models.TextField(blank=True, null=True)),
                (
                    "nomor_faktur",
                    models.CharField(
                        default=home.models.generate_faktur, max_length=12
                    ),
                ),
                ("tanggal_faktur", models.DateField()),
                ("pajak", models.FloatField(blank=True, null=True)),
                ("nominal_pajak", models.FloatField(blank=True, null=True)),
                ("diskon", models.FloatField(blank=True, null=True)),
                ("nominal_diskon", models.IntegerField(blank=True, null=True)),
                ("total", models.IntegerField(blank=True, null=True)),
                (
                    "sumber_dana",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.sumberdana",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pembelian",
                "verbose_name_plural": "Pembelian",
            },
        ),
        migrations.CreateModel(
            name="PembelianObat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=home.models.create_object_id,
                        max_length=32,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("nama_obat", models.CharField(blank=True, max_length=50, null=True)),
                ("jumlah", models.IntegerField(default=1)),
                ("harga", models.IntegerField()),
                ("diskon", models.FloatField(blank=True, null=True)),
                ("nominal_diskon", models.IntegerField(blank=True, null=True)),
                ("bonus", models.IntegerField(default=0)),
                ("tanggal_kedaluwarsa", models.DateField(blank=True, null=True)),
                (
                    "bonus_satuan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_satuan",
                        to="home.unit",
                    ),
                ),
                (
                    "obat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.produk",
                    ),
                ),
                (
                    "pembelian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.pembelian"
                    ),
                ),
                (
                    "satuan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obat",
                "verbose_name_plural": "Obat",
            },
        ),
    ]
