# Generated by Django 4.2.8 on 2024-07-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_produk_kemasan_metodepembayaran_sumber_dana_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="varianproduk",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.pembelian",
            ),
        ),
    ]
