# Generated by Django 4.2.8 on 2024-08-24 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_varianproduk_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produk",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.supplier",
            ),
        ),
    ]
